USE WAREHOUSE ADHOC_WH;
USE DATABASE DATAVELOCITY;
USE SCHEMA GOLD;

-- /*TODO: Create Orders marts*/
CREATE OR REPLACE TABLE GOLD.MART_ORDER (
    ORDER_ITEM_FACT_SK NUMBER AUTOINCREMENT COMMENT 'SURROGATE KEY (EDW)',
    ORDER_ITEM_ID NUMBER COMMENT 'ORDER ITEM FK (SOURCE SYSTEM)',
    ORDER_ID NUMBER COMMENT 'ORDER FK (SOURCE SYSTEM)',
    CUSTOMER_ID NUMBER COMMENT 'ORDER FK (SOURCE SYSTEM)',
    CUSTOMER_ADDRESS_ID NUMBER,
    RESTAURANT_ID NUMBER,
    LOCATION_ID NUMBER,
    MENU_ID NUMBER,
    DELIVERY_AGENT_ID NUMBER,
    ORDER_DATE_KEY NUMBER,
    QUANTITY NUMBER,
    PRICE NUMBER(10, 2),
    SUBTOTAL NUMBER(10, 2),
    DELIVERY_STATUS VARCHAR,
    ESTIMATED_TIME VARCHAR
);

MERGE INTO GOLD.MART_ORDER AS TARGET
USING (
    SELECT
        OI.ORDER_ITEM_ID,
        OI.ORDER_ID,

        C.CUSTOMER_ID,
        CA.CUSTOMER_ADDRESS_ID,
        R.RESTAURANT_ID,
        RL.LOCATION_ID,
        M.MENU_ID,
        DA.DELIVERY_AGENT_ID,

        DD.DIM_DATE_HK AS ORDER_DATE_KEY,

        OI.QUANTITY::NUMBER(2) AS QUANTITY,
        OI.PRICE,
        OI.SUBTOTAL,
        D.CURRENT_STATUS AS DELIVERY_STATUS,
        D.ESTIMATED_TIME

    FROM GOLD.FACT_ORDER_ITEM OI

    /* Mandatory facts */
    LEFT JOIN GOLD.FACT_ORDER O
        ON OI.ORDER_ID = O.ORDER_ID

    LEFT JOIN GOLD.FACT_DELIVERY D
        ON O.ORDER_ID = D.ORDER_ID

    /* Dimensions (LEFT JOIN) */
    LEFT JOIN GOLD.DIM_CUSTOMER C
        ON O.CUSTOMER_ID = C.CUSTOMER_ID

    LEFT JOIN GOLD.DIM_CUSTOMER_ADDRESS CA
        ON C.CUSTOMER_ID = CA.CUSTOMER_ID

    LEFT JOIN GOLD.DIM_RESTAURANT R
        ON O.RESTAURANT_ID = R.RESTAURANT_ID

    LEFT JOIN GOLD.DIM_LOCATION RL
        ON R.LOCATION_ID = RL.LOCATION_ID

    LEFT JOIN GOLD.DIM_MENU M
        ON OI.MENU_ID = M.MENU_ID

    LEFT JOIN GOLD.DIM_DELIVERY_AGENT DA
        ON D.DELIVERY_AGENT_ID = DA.DELIVERY_AGENT_ID

    LEFT JOIN GOLD.DIM_DATE DD
        ON DD.CALENDAR_DATE = DATE(O.ORDER_DATE)

) AS SOURCE
ON
    TARGET.ORDER_ITEM_ID = SOURCE.ORDER_ITEM_ID
    AND TARGET.ORDER_ID = SOURCE.ORDER_ID

WHEN MATCHED THEN
UPDATE SET
    TARGET.CUSTOMER_ID         = SOURCE.CUSTOMER_ID,
    TARGET.CUSTOMER_ADDRESS_ID = SOURCE.CUSTOMER_ADDRESS_ID,
    TARGET.RESTAURANT_ID       = SOURCE.RESTAURANT_ID,
    TARGET.LOCATION_ID         = SOURCE.LOCATION_ID,
    TARGET.MENU_ID             = SOURCE.MENU_ID,
    TARGET.DELIVERY_AGENT_ID   = SOURCE.DELIVERY_AGENT_ID,
    TARGET.ORDER_DATE_KEY      = SOURCE.ORDER_DATE_KEY,
    TARGET.QUANTITY            = SOURCE.QUANTITY,
    TARGET.PRICE               = SOURCE.PRICE,
    TARGET.SUBTOTAL            = SOURCE.SUBTOTAL,
    TARGET.DELIVERY_STATUS     = SOURCE.DELIVERY_STATUS,
    TARGET.ESTIMATED_TIME      = SOURCE.ESTIMATED_TIME

WHEN NOT MATCHED THEN
INSERT (
    ORDER_ITEM_ID,
    ORDER_ID,
    CUSTOMER_ID,
    CUSTOMER_ADDRESS_ID,
    RESTAURANT_ID,
    LOCATION_ID,
    MENU_ID,
    DELIVERY_AGENT_ID,
    ORDER_DATE_KEY,
    QUANTITY,
    PRICE,
    SUBTOTAL,
    DELIVERY_STATUS,
    ESTIMATED_TIME
)
VALUES (
    SOURCE.ORDER_ITEM_ID,
    SOURCE.ORDER_ID,
    SOURCE.CUSTOMER_ID,
    SOURCE.CUSTOMER_ADDRESS_ID,
    SOURCE.RESTAURANT_ID,
    SOURCE.LOCATION_ID,
    SOURCE.MENU_ID,
    SOURCE.DELIVERY_AGENT_ID,
    SOURCE.ORDER_DATE_KEY,
    SOURCE.QUANTITY,
    SOURCE.PRICE,
    SOURCE.SUBTOTAL,
    SOURCE.DELIVERY_STATUS,
    SOURCE.ESTIMATED_TIME
);