name: 'datavelocity_dbt'
version: '1.0.0'
config-version: 2

profile: 'datavelocity_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configure materialization and schema for each layer
models:
  datavelocity_dbt:
    bronze:
      +materialized: table
      +schema: bronze
      +tags: ['bronze', 'raw']
    silver:
      +materialized: table
      +schema: silver
      +tags: ['silver', 'cleansed']
    gold:
      +materialized: table
      +schema: gold
      +tags: ['gold', 'analytics']
      dimensions:
        +materialized: table
        +tags: ['dimension', 'scd2']
      facts:
        +materialized: incremental
        +on_schema_change: 'append_new_columns'
        +tags: ['fact', 'incremental']
      mart:
        +materialized: view