name: 'datavelocity_dbt'
version: '1.0.0'
config-version: 2

profile: 'datavelocity_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  datavelocity_dbt:
    gold:
      +materialized: table
      +schema: gold

      dimensions:
        +tags: ["dimension", "gold"]
        +materialized: table

      facts:
        +tags: ["fact", "gold"]
        +materialized: table

      analytics:
        +tags: ["mart", "analytics"]
        +materialized: table
        +schema: analytics  # Creates ANALYTICS schema instead of GOLD

        customer:
          +tags: ["mart", "customer"]

        delivery:
          +tags: ["mart", "delivery"]

        orders:
          +tags: ["mart", "orders"]

        restaurant:
          +tags: ["mart", "restaurant"]