-- ====================================================================================================
-- RESTAURANT
-- ====================================================================================================
-- CHANGE CONTEXT
USE ROLE ACCOUNTADMIN;
USE DATABASE SWIGGY;
USE SCHEMA BRONZE;
USE WAREHOUSE ADHOC_WH;

-- ----------------------------------------------------------------------------------------------------
-- CREATE RESTAURANT_BRZ
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.RESTAURANT_BRZ (
    RESTAURANT_BRZ_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME STRING ,                                                             -- RESTAURANT NAME, REQUIRED FIELD
    CUISINETYPE STRING,                                                       -- TYPE OF CUISINE OFFERED
    PRICING_FOR_2 STRING,                                                     -- PRICING FOR TWO PEOPLE AS TEXT
    RESTAURANT_PHONE STRING WITH TAG (COMMON.PII_POLICY_TAG = 'SENSITIVE'),   -- PHONE NUMBER AS TEXT
    OPERATINGHOURS STRING,                                                    -- RESTAURANT OPERATING HOURS
    LOCATION_ID STRING ,                                                       -- LOCATION ID, DEFAULT AS TEXT
    ACTIVEFLAG STRING ,                                                       -- ACTIVE STATUS
    OPENSTATUS STRING ,                                                       -- OPEN STATUS
    LOCALITY STRING,                                                          -- LOCALITY AS TEXT
    RESTAURANT_ADDRESS STRING,                                                -- ADDRESS AS TEXT
    LATITUDE STRING,                                                          -- LATITUDE AS TEXT FOR PRECISION
    LONGITUDE STRING,                                                         -- LONGITUDE AS TEXT FOR PRECISION
    BATCH_ID STRING,
    CREATED_AT STRING,                                                       -- RECORD CREATION DATE
    UPDATED_AT STRING                                                   -- LAST MODIFIED DATE
)
COMMENT = 'THIS IS THE RESTAURANT STAGE/RAW TABLE WHERE DATA WILL BE COPIED FROM INTERNAL STAGE USING COPY COMMAND. THIS IS AS-IS DATA REPRESETATION FROM THE SOURCE LOCATION. ALL THE COLUMNS ARE TEXT DATA TYPE EXCEPT THE AUDIT COLUMNS THAT ARE ADDED FOR TRACEABILITY.';

-- ----------------------------------------------------------------------------------------------------
-- CREATE RESTAURANT_SLV
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE SILVER.RESTAURANT_SLV (
    RESTAURANT_SLV_ID INTEGER PRIMARY KEY AUTOINCREMENT,              -- PRIMARY KEY WITH AUTO-INCREMENT
    NAME STRING(100),                                   -- RESTAURANT NAME, REQUIRED FIELD
    CUISINE_TYPE STRING,                                         -- TYPE OF CUISINE OFFERED
    PRICING_FOR_TWO NUMBER(10, 2),                               -- PRICING FOR TWO PEOPLE, UP TO 10 DIGITS WITH 2 DECIMAL PLACES
    RESTAURANT_PHONE STRING(15) WITH TAG (COMMON.PII_POLICY_TAG = 'SENSITIVE'),                                 -- PHONE NUMBER, SUPPORTS 10-DIGIT OR INTERNATIONAL FORMAT
    OPERATING_HOURS STRING(100),                                  -- RESTAURANT OPERATING HOURS
    LOCATION_ID_FK NUMBER,                                       -- REFERENCE ID FOR LOCATION, DEFAULTED TO 1
    ACTIVE_FLAG STRING(10),                                      -- INDICATES IF THE RESTAURANT IS ACTIVE
    OPEN_STATUS STRING(10),                                      -- INDICATES IF THE RESTAURANT IS CURRENTLY OPEN
    LOCALITY STRING(100),                                        -- LOCALITY OF THE RESTAURANT
    RESTAURANT_ADDRESS STRING,                                   -- ADDRESS OF THE RESTAURANT, SUPPORTS LONGER TEXT
    LATITUDE NUMBER(9,6),                                       -- LATITUDE WITH 6 DECIMAL PLACES FOR PRECISION
    LONGITUDE NUMBER(9,6),                                      -- LONGITUDE WITH 6 DECIMAL PLACES FOR PRECISION
    BATCH_ID STRING,
    CREATED_AT TIMESTAMP_TZ,                                     -- RECORD CREATION DATE
    UPDATED_AT TIMESTAMP_TZ                                 -- LAST MODIFIED DATE, ALLOWS NULL IF NOT MODIFIEDP
)
COMMENT = 'RESTAURANT ENTITY UNDER CLEAN SCHEMA WITH APPROPRIATE DATA TYPE UNDER CLEAN SCHEMA LAYER, DATA IS POPULATED USING MERGE STATEMENT FROM THE STAGE LAYER LOCATION TABLE. THIS TABLE DOES NOT SUPPORT SCD2';

-- ----------------------------------------------------------------------------------------------------
-- CREATE RESTAURANT_GLD
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE GOLD.DIM_RESTAURANT (
    RESTAURANT_ID NUMBER PRIMARY KEY,                   -- RESTAURANT ID WITHOUT AUTO-INCREMENT
    NAME STRING(100),                       -- RESTAURANT NAME
    CUISINE_TYPE STRING,                    -- TYPE OF CUISINE OFFERED
    PRICING_FOR_TWO NUMBER(10, 2),          -- PRICING FOR TWO PEOPLE
    RESTAURANT_PHONE STRING(15) WITH TAG (COMMON.PII_POLICY_TAG = 'SENSITIVE'),            -- RESTAURANT PHONE NUMBER
    OPERATING_HOURS STRING(100),            -- RESTAURANT OPERATING HOURS
    LOCATION_ID_FK NUMBER,                  -- FOREIGN KEY REFERENCE TO LOCATION
    ACTIVE_FLAG STRING(10),                 -- INDICATES IF THE RESTAURANT IS ACTIVE
    OPEN_STATUS STRING(10),                 -- INDICATES IF THE RESTAURANT IS CURRENTLY OPEN
    LOCALITY STRING(100),                   -- LOCALITY OF THE RESTAURANT
    RESTAURANT_ADDRESS STRING,              -- FULL ADDRESS OF THE RESTAURANT
    LATITUDE NUMBER(9, 6),                  -- LATITUDE FOR THE RESTAURANT'S LOCATION
    LONGITUDE NUMBER(9, 6),                 -- LONGITUDE FOR THE RESTAURANT'S LOCATION
    BATCH_ID STRING,
    STATUS BOOLEAN,                 -- INDICATES WHETHER THE RECORD IS THE CURRENT VERSION
    EFF_START_DATE TIMESTAMP_TZ,            -- EFFECTIVE START DATE FOR THE RECORD
    EFF_END_DATE TIMESTAMP_TZ            -- EFFECTIVE END DATE FOR THE RECORD (NULL IF ACTIVE)
)
COMMENT = 'DIMENSIONAL TABLE FOR RESTAURANT ENTITY WITH HASH KEYS AND SCD ENABLED.';

-- =====================================================
-- PROCEDURE 1: STAGE TO BRONZE
-- =====================================================
CREATE OR REPLACE PROCEDURE BRONZE.SP_RESTAURANT_STAGE_TO_BRONZE(
    P_BATCH_ID STRING,
    P_FILE_PATH STRING
)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    V_ROWS_LOADED INTEGER DEFAULT 0;
BEGIN
    -- CREATE TEMP TABLE
    CREATE OR REPLACE TEMPORARY TABLE TEMP_RESTAURANT_LOAD(
        NAME STRING,
        CUISINETYPE STRING,
        PRICING_FOR_2 STRING,
        RESTAURANT_PHONE STRING,
        OPERATINGHOURS STRING,
        LOCATION_ID STRING,
        ACTIVEFLAG STRING,
        OPENSTATUS STRING,
        LOCALITY STRING,
        RESTAURANT_ADDRESS STRING,
        LATITUDE STRING,
        LONGITUDE STRING
    );

    -- Copy data from stage to temp table
    EXECUTE IMMEDIATE
    '
        COPY INTO TEMP_RESTAURANT_LOAD (
            NAME, CUISINETYPE, PRICING_FOR_2, RESTAURANT_PHONE, OPERATINGHOURS,
            LOCATION_ID, ACTIVEFLAG, OPENSTATUS, LOCALITY, RESTAURANT_ADDRESS,
            LATITUDE, LONGITUDE
        )
        FROM (
            SELECT
                $1::STRING AS NAME,
                $2::STRING AS CUISINETYPE,
                $3::STRING AS PRICING_FOR_2,
                $4::STRING AS RESTAURANT_PHONE,
                $5::STRING AS OPERATINGHOURS,
                $6::STRING AS LOCATION_ID,
                $7::STRING AS ACTIVEFLAG,
                $8::STRING AS OPENSTATUS,
                $9::STRING AS LOCALITY,
                $10::STRING AS RESTAURANT_ADDRESS,
                $11::STRING AS LATITUDE,
                $12::STRING AS LONGITUDE
            FROM ' || P_FILE_PATH || '
        )
        FILE_FORMAT = (FORMAT_NAME = ''BRONZE.CSV_FILE_FORMAT'')
        ON_ERROR = ABORT_STATEMENT
    ';

    -- Insert into bronze table
    INSERT INTO BRONZE.RESTAURANT_BRZ (
        NAME, CUISINETYPE, PRICING_FOR_2, RESTAURANT_PHONE, OPERATINGHOURS,
        LOCATION_ID, ACTIVEFLAG, OPENSTATUS, LOCALITY, RESTAURANT_ADDRESS,
        LATITUDE, LONGITUDE, BATCH_ID, CREATED_AT, UPDATED_AT
    )
    SELECT
        NAME,
        CUISINETYPE,
        PRICING_FOR_2,
        RESTAURANT_PHONE,
        OPERATINGHOURS,
        LOCATION_ID,
        ACTIVEFLAG,
        OPENSTATUS,
        LOCALITY,
        RESTAURANT_ADDRESS,
        LATITUDE,
        LONGITUDE,
        :P_BATCH_ID,
        CURRENT_TIMESTAMP(),
        CURRENT_TIMESTAMP()
    FROM TEMP_RESTAURANT_LOAD;

    -- Get row count
    SELECT COUNT(*) INTO :V_ROWS_LOADED FROM TEMP_RESTAURANT_LOAD;

    -- Drop temp table
    DROP TABLE IF EXISTS TEMP_RESTAURANT_LOAD;

    RETURN 'Successfully loaded ' || :V_ROWS_LOADED || ' rows with batch_id: ' || :P_BATCH_ID;

EXCEPTION
    WHEN OTHER THEN
        RETURN 'Error occurred: ' || SQLERRM;
END;
$$;

-- =====================================================
-- PROCEDURE 2: BRONZE TO SILVER
-- =====================================================
CREATE OR REPLACE PROCEDURE SILVER.SP_RESTAURANT_BRONZE_TO_SILVER(
    P_BATCH_ID STRING
)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    V_ROWS_INSERTED INTEGER DEFAULT 0;
    V_ROWS_UPDATED INTEGER DEFAULT 0;
BEGIN
    -- Merge data from bronze to silver (no SCD2 at silver layer)
    MERGE INTO SILVER.RESTAURANT_SLV AS TGT
    USING (
        SELECT
            RESTAURANT_BRZ_ID,
            NAME,
            CUISINETYPE AS CUISINE_TYPE,
            TRY_CAST(PRICING_FOR_2 AS NUMBER(10, 2)) AS PRICING_FOR_TWO,
            RESTAURANT_PHONE,
            TRIM(OPERATINGHOURS) AS OPERATING_HOURS,
            TRY_CAST(LOCATION_ID AS NUMBER) AS LOCATION_ID_FK,
            CASE
                WHEN TRIM(LOWER(ACTIVEFLAG)) = 'yes' THEN TRUE ELSE FALSE
            END AS ACTIVE_FLAG,
            OPENSTATUS AS OPEN_STATUS,
            LOCALITY,
            RESTAURANT_ADDRESS,
            TRY_CAST(LATITUDE AS NUMBER(9, 6)) AS LATITUDE,
            TRY_CAST(LONGITUDE AS NUMBER(9, 6)) AS LONGITUDE,
            BATCH_ID,
            TRY_CAST(CREATED_AT AS TIMESTAMP_TZ) AS CREATED_AT,
            TRY_CAST(UPDATED_AT AS TIMESTAMP_TZ) AS UPDATED_AT
        FROM BRONZE.RESTAURANT_BRZ
        WHERE BATCH_ID = :P_BATCH_ID
    ) AS SRC
    ON TGT.RESTAURANT_SLV_ID = SRC.RESTAURANT_BRZ_ID

    WHEN MATCHED THEN
        UPDATE SET
            TGT.NAME = SRC.NAME,
            TGT.CUISINE_TYPE = SRC.CUISINE_TYPE,
            TGT.PRICING_FOR_TWO = SRC.PRICING_FOR_TWO,
            TGT.RESTAURANT_PHONE = SRC.RESTAURANT_PHONE,
            TGT.OPERATING_HOURS = SRC.OPERATING_HOURS,
            TGT.LOCATION_ID_FK = SRC.LOCATION_ID_FK,
            TGT.ACTIVE_FLAG = SRC.ACTIVE_FLAG,
            TGT.OPEN_STATUS = SRC.OPEN_STATUS,
            TGT.LOCALITY = SRC.LOCALITY,
            TGT.RESTAURANT_ADDRESS = SRC.RESTAURANT_ADDRESS,
            TGT.LATITUDE = SRC.LATITUDE,
            TGT.LONGITUDE = SRC.LONGITUDE,
            TGT.BATCH_ID = SRC.BATCH_ID,
            TGT.UPDATED_AT = SRC.UPDATED_AT

    WHEN NOT MATCHED THEN
        INSERT (
            NAME, CUISINE_TYPE, PRICING_FOR_TWO, RESTAURANT_PHONE, OPERATING_HOURS,
            LOCATION_ID_FK, ACTIVE_FLAG, OPEN_STATUS, LOCALITY, RESTAURANT_ADDRESS,
            LATITUDE, LONGITUDE, BATCH_ID, CREATED_AT, UPDATED_AT
        )
        VALUES (
            SRC.NAME, SRC.CUISINE_TYPE, SRC.PRICING_FOR_TWO, SRC.RESTAURANT_PHONE,
            SRC.OPERATING_HOURS, SRC.LOCATION_ID_FK, SRC.ACTIVE_FLAG, SRC.OPEN_STATUS,
            SRC.LOCALITY, SRC.RESTAURANT_ADDRESS, SRC.LATITUDE, SRC.LONGITUDE,
            SRC.BATCH_ID, SRC.CREATED_AT, SRC.UPDATED_AT
        );

    -- Get merge statistics
    V_ROWS_INSERTED := (SELECT COUNT(*) FROM SILVER.RESTAURANT_SLV WHERE BATCH_ID = :P_BATCH_ID);

    RETURN 'Successfully merged data. Batch_id: ' || :P_BATCH_ID ||
           '. Total rows processed: ' || :V_ROWS_INSERTED;

EXCEPTION
    WHEN OTHER THEN
        RETURN 'Error occurred: ' || SQLERRM;
END;
$$;

-- =====================================================
-- PROCEDURE 3: SILVER TO GOLD (WITH SCD2)
-- =====================================================
CREATE OR REPLACE PROCEDURE GOLD.SP_RESTAURANT_SILVER_TO_GOLD(
    P_BATCH_ID STRING
)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    V_CURRENT_TIMESTAMP TIMESTAMP_TZ;
    V_ROWS_EXPIRED INTEGER DEFAULT 0;
    V_ROWS_INSERTED INTEGER DEFAULT 0;
BEGIN
    V_CURRENT_TIMESTAMP := CURRENT_TIMESTAMP();

    -- Step 1: Expire records that have changed (set EFF_END_DATE and STATUS = FALSE)
    UPDATE GOLD.DIM_RESTAURANT AS TGT
    SET
        EFF_END_DATE = :V_CURRENT_TIMESTAMP,
        STATUS = FALSE
    FROM (
        SELECT
            SRC.RESTAURANT_SLV_ID,
            SRC.NAME,
            SRC.CUISINE_TYPE,
            SRC.PRICING_FOR_TWO,
            SRC.RESTAURANT_PHONE,
            SRC.OPERATING_HOURS,
            SRC.LOCATION_ID_FK,
            SRC.ACTIVE_FLAG,
            SRC.OPEN_STATUS,
            SRC.LOCALITY,
            SRC.RESTAURANT_ADDRESS,
            SRC.LATITUDE,
            SRC.LONGITUDE
        FROM SILVER.RESTAURANT_SLV SRC
        WHERE SRC.BATCH_ID = :P_BATCH_ID
    ) AS SRC
    WHERE TGT.RESTAURANT_ID = SRC.RESTAURANT_SLV_ID
        AND TGT.STATUS = TRUE
        AND (
            COALESCE(TGT.NAME, '') != COALESCE(SRC.NAME, '')
            OR COALESCE(TGT.CUISINE_TYPE, '') != COALESCE(SRC.CUISINE_TYPE, '')
            OR COALESCE(TGT.PRICING_FOR_TWO, 0) != COALESCE(SRC.PRICING_FOR_TWO, 0)
            OR COALESCE(TGT.RESTAURANT_PHONE, '') != COALESCE(SRC.RESTAURANT_PHONE, '')
            OR COALESCE(TGT.OPERATING_HOURS, '') != COALESCE(SRC.OPERATING_HOURS, '')
            OR COALESCE(TGT.LOCATION_ID_FK, 0) != COALESCE(SRC.LOCATION_ID_FK, 0)
            OR COALESCE(TGT.ACTIVE_FLAG, '') != COALESCE(SRC.ACTIVE_FLAG, '')
            OR COALESCE(TGT.OPEN_STATUS, '') != COALESCE(SRC.OPEN_STATUS, '')
            OR COALESCE(TGT.LOCALITY, '') != COALESCE(SRC.LOCALITY, '')
            OR COALESCE(TGT.RESTAURANT_ADDRESS, '') != COALESCE(SRC.RESTAURANT_ADDRESS, '')
            OR COALESCE(TGT.LATITUDE, 0) != COALESCE(SRC.LATITUDE, 0)
            OR COALESCE(TGT.LONGITUDE, 0) != COALESCE(SRC.LONGITUDE, 0)
        );

    -- Get count of expired rows
    V_ROWS_EXPIRED := SQLROWCOUNT;

    -- Step 2: Insert new records (both brand new and changed records)
    INSERT INTO GOLD.DIM_RESTAURANT (
        RESTAURANT_ID, NAME, CUISINE_TYPE, PRICING_FOR_TWO, RESTAURANT_PHONE,
        OPERATING_HOURS, LOCATION_ID_FK, ACTIVE_FLAG, OPEN_STATUS, LOCALITY,
        RESTAURANT_ADDRESS, LATITUDE, LONGITUDE, BATCH_ID, STATUS,
        EFF_START_DATE, EFF_END_DATE
    )
    SELECT
        SRC.RESTAURANT_SLV_ID AS RESTAURANT_ID,
        SRC.NAME,
        SRC.CUISINE_TYPE,
        SRC.PRICING_FOR_TWO,
        SRC.RESTAURANT_PHONE,
        SRC.OPERATING_HOURS,
        SRC.LOCATION_ID_FK,
        SRC.ACTIVE_FLAG,
        SRC.OPEN_STATUS,
        SRC.LOCALITY,
        SRC.RESTAURANT_ADDRESS,
        SRC.LATITUDE,
        SRC.LONGITUDE,
        SRC.BATCH_ID,
        TRUE AS STATUS,
        :V_CURRENT_TIMESTAMP AS EFF_START_DATE,
        NULL AS EFF_END_DATE
    FROM SILVER.RESTAURANT_SLV SRC
    WHERE SRC.BATCH_ID = :P_BATCH_ID
        AND NOT EXISTS (
            SELECT 1
            FROM GOLD.DIM_RESTAURANT TGT
            WHERE TGT.RESTAURANT_ID = SRC.RESTAURANT_SLV_ID
                AND TGT.STATUS = TRUE
                AND COALESCE(TGT.NAME, '') = COALESCE(SRC.NAME, '')
                AND COALESCE(TGT.CUISINE_TYPE, '') = COALESCE(SRC.CUISINE_TYPE, '')
                AND COALESCE(TGT.PRICING_FOR_TWO, 0) = COALESCE(SRC.PRICING_FOR_TWO, 0)
                AND COALESCE(TGT.RESTAURANT_PHONE, '') = COALESCE(SRC.RESTAURANT_PHONE, '')
                AND COALESCE(TGT.OPERATING_HOURS, '') = COALESCE(SRC.OPERATING_HOURS, '')
                AND COALESCE(TGT.LOCATION_ID_FK, 0) = COALESCE(SRC.LOCATION_ID_FK, 0)
                AND COALESCE(TGT.ACTIVE_FLAG, '') = COALESCE(SRC.ACTIVE_FLAG, '')
                AND COALESCE(TGT.OPEN_STATUS, '') = COALESCE(SRC.OPEN_STATUS, '')
                AND COALESCE(TGT.LOCALITY, '') = COALESCE(SRC.LOCALITY, '')
                AND COALESCE(TGT.RESTAURANT_ADDRESS, '') = COALESCE(SRC.RESTAURANT_ADDRESS, '')
                AND COALESCE(TGT.LATITUDE, 0) = COALESCE(SRC.LATITUDE, 0)
                AND COALESCE(TGT.LONGITUDE, 0) = COALESCE(SRC.LONGITUDE, 0)
        );

    -- Get count of inserted rows
    V_ROWS_INSERTED := SQLROWCOUNT;

    RETURN 'SCD2 processing completed successfully. Batch_id: ' || :P_BATCH_ID ||
           '. Rows expired: ' || :V_ROWS_EXPIRED ||
           '. New rows inserted: ' || :V_ROWS_INSERTED;

EXCEPTION
    WHEN OTHER THEN
        RETURN 'Error occurred: ' || SQLERRM;
END;
$$;

-- =====================================================
-- Query to see history of a specific restaurant
SELECT * FROM GOLD.DIM_RESTAURANT
WHERE RESTAURANT_ID = 123
ORDER BY EFF_START_DATE;

-- Query to see restaurants with price changes
SELECT
    RESTAURANT_ID,
    NAME,
    PRICING_FOR_TWO,
    ACTIVE_FLAG,
    OPEN_STATUS,
    EFF_START_DATE,
    EFF_END_DATE,
    STATUS
FROM GOLD.DIM_RESTAURANT
WHERE RESTAURANT_ID IN (
    SELECT RESTAURANT_ID
    FROM GOLD.DIM_RESTAURANT
    GROUP BY RESTAURANT_ID
    HAVING COUNT(*) > 1
)
ORDER BY RESTAURANT_ID, EFF_START_DATE;

-- Query to find restaurants that changed operating hours
SELECT
    RESTAURANT_ID,
    NAME,
    OPERATING_HOURS,
    EFF_START_DATE,
    EFF_END_DATE
FROM GOLD.DIM_RESTAURANT
WHERE STATUS = FALSE
    AND EFF_END_DATE IS NOT NULL
ORDER BY EFF_END_DATE DESC;
-- ====================================================================================================