-- =====================================================
-- KAFKA TABLES, STREAMING & TASKS SETUP FOR SNOWPIPE STREAMING
-- =====================================================
USE ROLE ACCOUNTADMIN;
USE DATABASE DATAVELOCITY;
USE SCHEMA BRONZE;
USE WAREHOUSE ADHOC_WH;

-- =====================================================
-- BRONZE LAYER - STREAM TABLES
-- =====================================================

-- 1. ORDERS STREAM TABLE
CREATE OR REPLACE TABLE BRONZE.ORDERS_STREAM (
    -- Kafka metadata (raw storage only)
    RECORD_METADATA VARIANT,
    RECORD_CONTENT VARIANT,

    -- Processing flags (no default values)
    INGESTED_AT TIMESTAMP_TZ,
    PROCESSED_TO_GOLD BOOLEAN,
    BATCH_ID VARCHAR(36)
)
COMMENT = 'Stream table for real-time order events from Kafka';

-- 2. ORDER ITEMS STREAM TABLE
CREATE OR REPLACE TABLE BRONZE.ORDER_ITEMS_STREAM (
    -- Kafka metadata (raw storage only)
    RECORD_METADATA VARIANT,
    RECORD_CONTENT VARIANT,

    -- Processing flags (no default values)
    INGESTED_AT TIMESTAMP_TZ,
    PROCESSED_TO_GOLD BOOLEAN,
    BATCH_ID VARCHAR(36)
)
COMMENT = 'Stream table for real-time order item events from Kafka';

-- 3. DELIVERY STREAM TABLE
CREATE OR REPLACE TABLE BRONZE.DELIVERY_STREAM (
    -- Kafka metadata (raw storage only)
    RECORD_METADATA VARIANT,
    RECORD_CONTENT VARIANT,
    INGESTED_AT TIMESTAMP_TZ,
    PROCESSED_TO_GOLD BOOLEAN,
    BATCH_ID VARCHAR(36)
)
COMMENT = 'Stream table for real-time delivery events from Kafka';

-- =====================================================
-- CREATE VIEWS FOR QUERYING
-- =====================================================

-- View for Orders
CREATE OR REPLACE VIEW BRONZE.V_ORDERS_STREAM AS
SELECT
    -- Kafka metadata
    RECORD_METADATA:offset::NUMBER AS KAFKA_OFFSET,
    RECORD_METADATA:partition::NUMBER AS KAFKA_PARTITION,
    TO_TIMESTAMP(RECORD_METADATA:CreateTime::NUMBER, 3) AS KAFKA_TIMESTAMP,

    -- Event data
    RECORD_CONTENT:event_type::VARCHAR AS EVENT_TYPE,
    TO_TIMESTAMP_TZ(RECORD_CONTENT:event_timestamp::STRING) AS EVENT_TIMESTAMP,

    -- Order data
    RECORD_CONTENT:order_id::VARCHAR AS ORDER_ID,
    RECORD_CONTENT:customer_id::VARCHAR AS CUSTOMER_ID,
    RECORD_CONTENT:restaurant_id::INTEGER AS RESTAURANT_ID,
    RECORD_CONTENT:order_date::TIMESTAMP_TZ AS ORDER_DATE,
    RECORD_CONTENT:total_amount::NUMBER(10,2) AS TOTAL_AMOUNT,
    RECORD_CONTENT:status::VARCHAR AS STATUS,
    RECORD_CONTENT:payment_method::VARCHAR AS PAYMENT_METHOD,

    -- Processing flags
    INGESTED_AT,
    PROCESSED_TO_GOLD,
    BATCH_ID
FROM BRONZE.ORDERS_STREAM;

-- View for Order Items
CREATE OR REPLACE VIEW BRONZE.V_ORDER_ITEMS_STREAM AS
SELECT
    -- Kafka metadata
    RECORD_METADATA:offset::NUMBER AS KAFKA_OFFSET,
    RECORD_METADATA:partition::NUMBER AS KAFKA_PARTITION,
    TO_TIMESTAMP(RECORD_METADATA:CreateTime::NUMBER, 3) AS KAFKA_TIMESTAMP,

    -- Event data
    RECORD_CONTENT:event_type::VARCHAR AS EVENT_TYPE,
    TO_TIMESTAMP_TZ(RECORD_CONTENT:event_timestamp::STRING) AS EVENT_TIMESTAMP,

    -- Order item data
    RECORD_CONTENT:order_item_id::VARCHAR AS ORDER_ITEM_ID,
    RECORD_CONTENT:order_id::VARCHAR AS ORDER_ID,
    RECORD_CONTENT:menu_id::INTEGER AS MENU_ID,
    RECORD_CONTENT:quantity::INTEGER AS QUANTITY,
    RECORD_CONTENT:price::NUMBER(10,2) AS PRICE,
    RECORD_CONTENT:subtotal::NUMBER(10,2) AS SUBTOTAL,

    -- Processing flags
    INGESTED_AT,
    PROCESSED_TO_GOLD,
    BATCH_ID
FROM BRONZE.ORDER_ITEMS_STREAM;

-- View for Delivery
CREATE OR REPLACE VIEW BRONZE.V_DELIVERY_STREAM AS
SELECT
    -- Kafka metadata
    RECORD_METADATA:offset::NUMBER AS KAFKA_OFFSET,
    RECORD_METADATA:partition::NUMBER AS KAFKA_PARTITION,
    TO_TIMESTAMP(RECORD_METADATA:CreateTime::NUMBER, 3) AS KAFKA_TIMESTAMP,

    -- Event data
    RECORD_CONTENT:event_type::VARCHAR AS EVENT_TYPE,
    TO_TIMESTAMP_TZ(RECORD_CONTENT:event_timestamp::STRING) AS EVENT_TIMESTAMP,

    -- Delivery data
    RECORD_CONTENT:delivery_id::VARCHAR AS DELIVERY_ID,
    RECORD_CONTENT:order_id::VARCHAR AS ORDER_ID,
    RECORD_CONTENT:delivery_agent_id::INTEGER AS DELIVERY_AGENT_ID,
    RECORD_CONTENT:delivery_status::VARCHAR AS DELIVERY_STATUS,
    RECORD_CONTENT:estimated_time::TIMESTAMP_TZ AS ESTIMATED_TIME,
    RECORD_CONTENT:customer_address_id::INTEGER AS CUSTOMER_ADDRESS_ID,
    RECORD_CONTENT:delivery_date::TIMESTAMP_TZ AS DELIVERY_DATE,
    RECORD_CONTENT:location::VARIANT AS LOCATION,

    -- Processing flags
    INGESTED_AT,
    PROCESSED_TO_GOLD,
    BATCH_ID
FROM BRONZE.DELIVERY_STREAM;

-- =====================================================
-- CREATE SNOWFLAKE STREAMS (CDC)
-- =====================================================

-- Stream for Orders
CREATE OR REPLACE STREAM BRONZE.STREAM_ORDERS_CHANGES
ON TABLE BRONZE.ORDERS_STREAM
APPEND_ONLY = TRUE
COMMENT = 'Captures new order records for Gold layer processing';

-- Stream for Order Items
CREATE OR REPLACE STREAM BRONZE.STREAM_ORDER_ITEM_CHANGES
ON TABLE BRONZE.ORDER_ITEMS_STREAM
APPEND_ONLY = TRUE
COMMENT = 'Captures new order item records for Gold layer processing';

-- Stream for Delivery
CREATE OR REPLACE STREAM BRONZE.STREAM_DELIVERY_CHANGES
ON TABLE BRONZE.DELIVERY_STREAM
APPEND_ONLY = TRUE
COMMENT = 'Captures new delivery records for Gold layer processing';

-- =====================================================
-- GRANT PERMISSIONS TO KAFKA ROLE
-- =====================================================

GRANT SELECT, INSERT ON TABLE BRONZE.ORDERS_STREAM TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT SELECT, INSERT ON TABLE BRONZE.ORDER_ITEMS_STREAM TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT SELECT, INSERT ON TABLE BRONZE.DELIVERY_STREAM TO ROLE KAFKA_CONNECTOR_ROLE;

-- =====================================================
-- CREATE SNOWFLAKE TASKS
-- =====================================================

-- Task for Orders (every 5 minutes)
CREATE OR REPLACE TASK BRONZE.TASK_ORDERS_STREAM_TO_GOLD
    WAREHOUSE = ADHOC_WH
    SCHEDULE = '2 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_ORDERS_CHANGES')
AS
CALL COMMON.SP_UNIVERSAL_ETL_MASTER('ORDER_STREAM', NULL);

-- Task for Order Items (every 5 minutes)
CREATE OR REPLACE TASK BRONZE.TASK_ORDER_ITEMS_STREAM_TO_GOLD
    WAREHOUSE = ADHOC_WH
    SCHEDULE = '3 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_ORDER_ITEM_CHANGES')
AS
CALL COMMON.SP_UNIVERSAL_ETL_MASTER('ORDER_ITEM_STREAM', NULL);

-- Task for Delivery (every 2 minutes - more frequent)
CREATE OR REPLACE TASK BRONZE.TASK_DELIVERY_STREAM_TO_GOLD
    WAREHOUSE = ADHOC_WH
    SCHEDULE = '4 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_DELIVERY_CHANGES')
AS
CALL COMMON.SP_UNIVERSAL_ETL_MASTER('DELIVERY_STREAM', NULL);

-- Resume all tasks
ALTER TASK BRONZE.TASK_ORDERS_STREAM_TO_GOLD RESUME;
ALTER TASK BRONZE.TASK_ORDER_ITEMS_STREAM_TO_GOLD RESUME;
ALTER TASK BRONZE.TASK_DELIVERY_STREAM_TO_GOLD RESUME;
-- =====================================================
-- MONITORING QUERIES
-- =====================================================
STOP;
-- Check stream status
SELECT
    'BRONZE.STREAM_ORDERS_CHANGES' AS STREAM_NAME,
    SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_ORDERS_CHANGES') AS HAS_DATA
UNION ALL
SELECT
    'BRONZE.STREAM_ORDER_ITEMS_CHANGES',
    SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_ORDER_ITEMS_CHANGES')
UNION ALL
SELECT
    'BRONZE.STREAM_DELIVERY_CHANGES',
    SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_DELIVERY_CHANGES');

-- Check recent data in streams
SELECT COUNT(*) AS ORDERS_COUNT FROM BRONZE.STREAM_ORDERS_CHANGES;
SELECT COUNT(*) AS ORDER_ITEMS_COUNT FROM BRONZE.STREAM_ORDER_ITEMS_CHANGES;
SELECT COUNT(*) AS DELIVERY_COUNT FROM BRONZE.STREAM_DELIVERY_CHANGES;

-- View sample data using views
SELECT * FROM BRONZE.V_ORDERS_STREAM LIMIT 10;
SELECT * FROM BRONZE.V_ORDER_ITEMS_STREAM LIMIT 10;
SELECT * FROM BRONZE.V_DELIVERY_STREAM LIMIT 10;

SELECT * FROM GOLD.FACT_DELIVERY WHERE BATCH_ID LIKE 'STREAM%';
SELECT * FROM GOLD.FACT_ORDER_ITEM WHERE BATCH_ID LIKE 'STREAM%';
SELECT * FROM GOLD.FACT_ORDER WHERE BATCH_ID LIKE 'STREAM%';

SELECT * FROM STREAM_DELIVERY_CHANGES;
SELECT * FROM STREAM_ORDERS_CHANGES;
SELECT * FROM STREAM_ORDER_ITEM_CHANGES;

SELECT * FROM BRONZE.DELIVERY_STREAM;
SELECT * FROM BRONZE.ORDERS_STREAM;
SELECT * FROM BRONZE.ORDER_ITEMS_STREAM;

SELECT * FROM GOLD.FACT_DELIVERY WHERE BATCH_ID LIKE 'STREAM_%';
SELECT * FROM GOLD.FACT_ORDER WHERE BATCH_ID LIKE 'STREAM_%';
SELECT * FROM GOLD.FACT_ORDER_ITEM WHERE BATCH_ID LIKE 'STREAM_%';

SELECT * FROM COMMON.PIPELINE_EXECUTION_RESULT;

SELECT * FROM COMMON.VW_TASK_EXECUTION_STATUS;
SELECT CURRENT_TIMESTAMP();

select batch_id, max(created_at),count(*) from gold.fact_order group by batch_id order by 2 desc;
select batch_id, max(created_at),count(*) from gold.fact_order_item group by batch_id  order by 2 desc;
select batch_id, max(created_at),count(*) from gold.fact_delivery group by batch_id order by 2 desc;

select * from gold.fact_order order by created_at desc;
select * from gold.fact_order order by created_at desc;


select record_content, record_content:event_timestamp from orders_stream order by 2 desc;
select record_content, record_content:event_timestamp from order_items_stream order by 2 desc;
select record_content, record_content:event_timestamp from delivery_stream order by 2 desc;

