-- =====================================================
-- SNOWFLAKE KAFKA USER SETUP
-- =====================================================
USE ROLE ACCOUNTADMIN;

-- Create Kafka role
CREATE ROLE IF NOT EXISTS KAFKA_CONNECTOR_ROLE;

-- Database & warehouse usage
GRANT USAGE ON DATABASE DATAVELOCITY TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT USAGE ON WAREHOUSE ADHOC_WH TO ROLE KAFKA_CONNECTOR_ROLE;

-- Bronze schema access only
GRANT USAGE ON SCHEMA DATAVELOCITY.BRONZE TO ROLE KAFKA_CONNECTOR_ROLE;

-- Allow Kafka to insert data
GRANT INSERT ON ALL TABLES IN SCHEMA DATAVELOCITY.BRONZE TO ROLE KAFKA_CONNECTOR_ROLE;

-- Future tables safety
GRANT INSERT ON FUTURE TABLES IN SCHEMA DATAVELOCITY.BRONZE TO ROLE KAFKA_CONNECTOR_ROLE;

-- Create user for Kafka Connect
-- CREATE USER KAFKA_CONNECT_USER
--     RSA_PUBLIC_KEY = '<RSA_PUBLIC_KEY>'
--     DEFAULT_ROLE = KAFKA_CONNECTOR_ROLE
--     DEFAULT_WAREHOUSE = ADHOC_WH
--     DEFAULT_NAMESPACE = DATAVELOCITY.SILVER;

-- -- Grant role to user
-- GRANT ROLE KAFKA_CONNECTOR_ROLE TO USER KAFKA_CONNECT_USER;
-- GRANT ROLE KAFKA_CONNECTOR_ROLE TO ROLE ACCOUNTADMIN;

-- -- Verify user creation
-- SHOW USERS LIKE 'KAFKA_CONNECT_USER';
-- DESC USER KAFKA_CONNECT_USER;
-- -- ALTER USER KAFKA_CONNECT_USER
-- -- UNSET RSA_PUBLIC_KEY;
