{{
    config(
        materialized='view',
        tags=['analytics', 'delivery', 'daily'],
        cluster_by=['PERFORMANCE_TIER'],
        description='Delivery agent performance metrics and rankings'
    )
}}

SELECT
    da.DELIVERY_AGENT_ID,
    da.DELIVERY_AGENT_NAME,
    da.PHONE,
    da.VEHICLE_TYPE,
    da.GENDER,
    da.RATING AS CURRENT_RATING,
    l.CITY,
    l.STATE,

    -- Delivery Metrics
    COUNT(DISTINCT fd.DELIVERY_ID) AS TOTAL_DELIVERIES,
    SUM(CASE WHEN fd.CURRENT_STATUS = 'DELIVERED' THEN 1 ELSE 0 END) AS SUCCESSFUL_DELIVERIES,
    SUM(CASE WHEN fd.CURRENT_STATUS = 'FAILED' THEN 1 ELSE 0 END) AS FAILED_DELIVERIES,
    SUM(CASE WHEN fd.CURRENT_STATUS = 'CANCELLED' THEN 1 ELSE 0 END) AS CANCELLED_DELIVERIES,

    -- Success Rate
    DIV0(SUM(CASE WHEN fd.CURRENT_STATUS = 'DELIVERED' THEN 1 ELSE 0 END),
         COUNT(*)) * 100 AS SUCCESS_RATE,

    -- Time Metrics
    AVG(TRY_CAST(REGEXP_REPLACE(fd.ESTIMATED_TIME, '[^0-9]', '') AS INTEGER)) AS AVG_ESTIMATED_TIME_MINS,

    -- Date Ranges
    MIN(fd.DELIVERY_DATE) AS FIRST_DELIVERY_DATE,
    MAX(fd.DELIVERY_DATE) AS LAST_DELIVERY_DATE,
    DATEDIFF(DAY, MIN(fd.DELIVERY_DATE), MAX(fd.DELIVERY_DATE)) AS TENURE_DAYS,

    -- Daily Averages
    DIV0(COUNT(DISTINCT fd.DELIVERY_ID),
         NULLIF(COUNT(DISTINCT DATE(fd.DELIVERY_DATE)), 0)) AS AVG_DELIVERIES_PER_DAY,

    -- Performance Tier
    CASE
        WHEN DIV0(SUM(CASE WHEN fd.CURRENT_STATUS = 'DELIVERED' THEN 1 ELSE 0 END), COUNT(*)) * 100 >= 95
            AND COUNT(DISTINCT fd.DELIVERY_ID) >= 100 THEN 'EXCELLENT'
        WHEN DIV0(SUM(CASE WHEN fd.CURRENT_STATUS = 'DELIVERED' THEN 1 ELSE 0 END), COUNT(*)) * 100 >= 90 THEN 'GOOD'
        WHEN DIV0(SUM(CASE WHEN fd.CURRENT_STATUS = 'DELIVERED' THEN 1 ELSE 0 END), COUNT(*)) * 100 >= 80 THEN 'AVERAGE'
        ELSE 'NEEDS_IMPROVEMENT'
    END AS PERFORMANCE_TIER,

    CURRENT_TIMESTAMP() AS CREATED_AT
FROM {{ ref('dim_delivery_agent') }} da
LEFT JOIN {{ ref('fact_delivery') }} fd
    ON da.DELIVERY_AGENT_ID = fd.DELIVERY_AGENT_ID
LEFT JOIN {{ ref('dim_location') }} l
    ON da.LOCATION_ID = l.LOCATION_ID
WHERE da.STATUS = 'ACTIVE'
GROUP BY
    da.DELIVERY_AGENT_ID, da.DELIVERY_AGENT_NAME, da.PHONE,
    da.VEHICLE_TYPE, da.GENDER, da.RATING, l.CITY, l.STATE