{{
    config(
        materialized='view',
        tags=['analytics', 'restaurant', 'daily'],
        cluster_by=['RESTAURANT_TIER', 'CITY'],
        description='Comprehensive restaurant performance metrics'
    )
}}

SELECT
    r.RESTAURANT_ID,
    r.RESTAURANT_NAME,
    r.CUISINE_TYPE,
    r.PRICING_FOR_TWO,
    r.LOCALITY,
    l.CITY,
    l.STATE,
    l.CITY_TIER,
    r.OPEN_STATUS,

    -- Order Metrics
    COUNT(DISTINCT o.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT o.CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
    SUM(o.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    AVG(o.TOTAL_AMOUNT) AS AVG_ORDER_VALUE,

    -- Customer Retention
    DIV0(COUNT(DISTINCT o.ORDER_ID),
         COUNT(DISTINCT o.CUSTOMER_ID)) AS ORDERS_PER_CUSTOMER,

    -- Order Status
    SUM(CASE WHEN o.CURRENT_STATUS = 'COMPLETED' THEN 1 ELSE 0 END) AS COMPLETED_ORDERS,
    SUM(CASE WHEN o.CURRENT_STATUS = 'CANCELLED' THEN 1 ELSE 0 END) AS CANCELLED_ORDERS,
    DIV0(SUM(CASE WHEN o.CURRENT_STATUS = 'CANCELLED' THEN 1 ELSE 0 END),
         COUNT(*)) * 100 AS CANCELLATION_RATE,

    -- Time Metrics
    MIN(o.ORDER_DATE) AS FIRST_ORDER_DATE,
    MAX(o.ORDER_DATE) AS LAST_ORDER_DATE,
    DATEDIFF(DAY, MIN(o.ORDER_DATE), MAX(o.ORDER_DATE)) AS OPERATIONAL_DAYS,

    -- Daily Averages
    DIV0(COUNT(DISTINCT o.ORDER_ID),
         NULLIF(COUNT(DISTINCT DATE(o.ORDER_DATE)), 0)) AS AVG_ORDERS_PER_DAY,
    DIV0(SUM(o.TOTAL_AMOUNT),
         NULLIF(COUNT(DISTINCT DATE(o.ORDER_DATE)), 0)) AS AVG_REVENUE_PER_DAY,

    -- Performance Tier
    CASE
        WHEN COUNT(DISTINCT o.ORDER_ID) >= 500 AND AVG(o.TOTAL_AMOUNT) >= 500 THEN 'PLATINUM'
        WHEN COUNT(DISTINCT o.ORDER_ID) >= 200 AND AVG(o.TOTAL_AMOUNT) >= 300 THEN 'GOLD'
        WHEN COUNT(DISTINCT o.ORDER_ID) >= 50 THEN 'SILVER'
        ELSE 'BRONZE'
    END AS RESTAURANT_TIER,

    CURRENT_TIMESTAMP() AS CREATED_AT
FROM {{ ref('dim_restaurant') }} r
LEFT JOIN {{ ref('fact_order') }} o
    ON r.RESTAURANT_ID = o.RESTAURANT_ID
LEFT JOIN {{ ref('dim_location') }} l
    ON r.LOCATION_ID = l.LOCATION_ID
WHERE r.STATUS = 'ACTIVE'
GROUP BY
    r.RESTAURANT_ID, r.RESTAURANT_NAME, r.CUISINE_TYPE, r.PRICING_FOR_TWO,
    r.LOCALITY, l.CITY, l.STATE, l.CITY_TIER, r.OPEN_STATUS